name: Merge PR to dev on "merge dev" comment

on:
  issue_comment:
    types: [created]

jobs:
  pull_request_comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, 'merge dev')
    steps:
      - uses: actions/checkout@v2

      - name: Start comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               -X POST \
               -d "{\"body\": \"dev 에 머지 시작\"}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"

      - name: Check if dev branch exists
        id: check_dev_branch
        run: |
          if git show-ref --verify --quiet refs/heads/dev; then
            echo "dev branch exists."
            echo "::set-output name=exists::true"
          else
            echo "dev branch does not exist."
            echo "::set-output name=exists::false"
          fi

      - name: Create dev branch from main if not exists
        if: steps.check_dev_branch.outputs.exists == 'false'
        run: |
          git checkout main
          git checkout -b dev
          git push origin dev

      - name: Merge PR branch to dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_BRANCH=$(jq -r .pull_request.head.ref < "${{ github.event_path }}")
          git checkout dev
          git merge --no-ff origin/$PR_BRANCH -m "Merged PR #${{ github.event.issue.number }} from $PR_BRANCH to dev"
          git push origin dev
